[package]
name = "audio-cd-ripper"
version = "0.3.0"
edition = "2024"
description = "Audio CD ripper for Windows, macOS and Linux with automatic metadata fetching"
repository = "https://github.com/Bloomca/audio-cd-ripper"
license = "MIT"
keywords = ["audio-cd", "cd-da", "ripper"]
categories = ["command-line-utilities", "multimedia::audio"]
exclude = ["target", "Cargo.lock"]

[dependencies]
base64 = "0.22.1"
cd-da-reader = "0.4.1"
flac-codec = "1.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha1 = "0.10.6"
ureq = { version = "3.1.0", features = ["json"] }
